# This file contains information about the device associated with this repo
# This is a .properties file, but is also interpreted as a Makefile,
# so keep the syntax simple: NAME=VALUE
DEV_MFR=Adafruit
DEV_NAME=FT232H Breakout
DEV_PN=2246
DEV_VER=
DEV_TAG=Adafruit_FT232H_Breakout_2246
